server:
  port: 8083

spring:
  application:
    name: passenger-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.203.132:3306/ride_sharing
    username: root
    password: wengyehao123
  cloud:
    nacos:
      server-addr: 192.168.203.132
      #暂未用到配置中心功能，需要关闭配置检查
      config:
        import-check:
          enabled: false
    openfeign:
      okhttp:
        enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #mybatis-plus自动打开驼峰映射，mybatis则自动关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1 #被删除
      logic-not-delete-value: 0 #正常

ride-sharing:
  jwt:
    secret-key: weng
